version: '3.9'

services:
  database:
    container_name: pre-project-database
    image: postgres:14-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASS}
      TZ: ${TZ}
    volumes:
      - './postgres:/var/lib/postgresql/data'
    ports:
      - '5555:5432'